[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:8000" # Defaults to local, overriden in Netlify UI for production using the Cloudflare Tunnel URL.
